#!/usr/bin/env npx tsx
/**
 * Bootstrap vault + agent + policy for elizaOS.
 *
 * Uses a HUMAN API key (1ck_...) only during this script to create resources.
 * The human key is never written to disk or printed. Output is agent-only (ocv_).
 *
 * Usage:
 *   ONECLAW_HUMAN_API_KEY=1ck_... npm run bootstrap
 *   ONECLAW_HUMAN_API_KEY=1ck_... npx tsx scripts/bootstrap.ts
 */

import { existsSync, writeFileSync } from "node:fs";
import { createInterface } from "node:readline";
import { createClient } from "@1claw/sdk";

const BASE_URL = process.env.ONECLAW_BASE_URL ?? "https://api.1claw.xyz";
const AGENT_NAME = process.env.ONECLAW_AGENT_NAME ?? "elizaos-agent";
const VAULT_NAME = process.env.ONECLAW_VAULT_NAME ?? "elizaos-vault";
const POLICY_PATH = process.env.ONECLAW_POLICY_PATH ?? "**";
const OUTPUT_FILE = process.env.ONECLAW_OUTPUT_FILE ?? ".env.elizaos";
const ENABLE_INTENTS =
  process.env.ONECLAW_ENABLE_INTENTS === "1" ||
  process.env.ONECLAW_ENABLE_INTENTS === "true";
const ENABLE_SHROUD =
  process.env.ONECLAW_USE_SHROUD === "1" ||
  process.env.ONECLAW_USE_SHROUD === "true";

function fail(msg: string): never {
  console.error(`Error: ${msg}`);
  process.exit(1);
}

function info(msg: string): void {
  console.log(msg);
}

async function readHumanKey(): Promise<string> {
  const fromEnv = process.env.ONECLAW_HUMAN_API_KEY?.trim();
  if (fromEnv) return fromEnv;

  if (!process.stdin.isTTY) {
    fail(
      "Set ONECLAW_HUMAN_API_KEY (1ck_...) in the environment. Interactive prompt requires a TTY.",
    );
  }

  const rl = createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  return new Promise((resolve) => {
    rl.question(
      "Human API key (1ck_..., used only for setup, not stored): ",
      (answer) => {
        rl.close();
        resolve(answer.trim());
      },
    );
  });
}

function validateHumanKey(key: string): void {
  if (!key) fail("Human API key is required.");
  if (key.startsWith("ocv_")) {
    fail(
      "You passed an agent key (ocv_). Use a human key (1ck_...) from the dashboard → API Keys.",
    );
  }
  if (key.startsWith("plt_")) {
    fail("Platform keys (plt_...) cannot provision agents. Use a human key (1ck_...).");
  }
  if (!key.startsWith("1ck_")) {
    fail("Expected a human API key starting with 1ck_.");
  }
}

async function main(): Promise<void> {
  info("1Claw elizaOS bootstrap");
  info("Human key is used only to create vault, agent, and policy — never saved.\n");

  const humanKey = await readHumanKey();
  validateHumanKey(humanKey);

  const client = createClient({ baseUrl: BASE_URL });

  info("Authenticating with human API key (one-time)...");
  const authRes = await client.auth.apiKeyToken({ api_key: humanKey });
  if (authRes.error || !authRes.data?.access_token) {
    fail(authRes.error?.message ?? "Failed to exchange human API key for JWT");
  }
  info("Authenticated.\n");

  info(`Creating vault "${VAULT_NAME}"...`);
  const vaultRes = await client.vault.create({
    name: VAULT_NAME,
    description: "Vault for elizaOS agent (bootstrap script)",
  });
  if (vaultRes.error || !vaultRes.data?.id) {
    fail(vaultRes.error?.message ?? "Failed to create vault");
  }
  const vaultId = vaultRes.data.id;
  info(`  vault_id: ${vaultId}\n`);

  info(`Creating agent "${AGENT_NAME}"...`);
  const agentRes = await client.agents.create({
    name: AGENT_NAME,
    description: "elizaOS character agent (created by @1claw/plugin-elizaos bootstrap)",
    auth_method: "api_key",
    vault_ids: [vaultId],
    intents_api_enabled: ENABLE_INTENTS,
    shroud_enabled: ENABLE_SHROUD,
  });
  if (agentRes.error || !agentRes.data?.agent?.id) {
    fail(agentRes.error?.message ?? "Failed to create agent");
  }
  const agentId = agentRes.data.agent.id;
  const agentApiKey = agentRes.data.api_key;
  if (!agentApiKey) {
    fail("Agent created but no api_key returned (auth_method must be api_key)");
  }
  info(`  agent_id: ${agentId}`);
  info(`  agent API key issued (ocv_..., shown once below)\n`);

  info(`Creating access policy (path: ${POLICY_PATH})...`);
  const policyRes = await client.access.grantAgent(vaultId, agentId, ["read", "write"], {
    secretPathPattern: POLICY_PATH,
  });
  if (policyRes.error || !policyRes.data?.id) {
    fail(policyRes.error?.message ?? "Failed to create policy");
  }
  info(`  policy_id: ${policyRes.data.id}\n`);

  const envLines = [
    "# Generated by 1claw-elizaos bootstrap — agent credentials only",
    "# Do NOT put your human API key (1ck_) in this file.",
    `ONECLAW_AGENT_API_KEY=${agentApiKey}`,
    `ONECLAW_AGENT_ID=${agentId}`,
    `ONECLAW_VAULT_ID=${vaultId}`,
    `ONECLAW_BASE_URL=${BASE_URL}`,
    ENABLE_SHROUD ? "ONECLAW_USE_SHROUD=true" : "# ONECLAW_USE_SHROUD=false",
    "",
  ].join("\n");

  if (existsSync(OUTPUT_FILE)) {
    fail(
      `${OUTPUT_FILE} already exists. Remove it or set ONECLAW_OUTPUT_FILE to another path.`,
    );
  }
  writeFileSync(OUTPUT_FILE, envLines, { mode: 0o600 });
  info(`Wrote agent credentials to ${OUTPUT_FILE} (mode 600)\n`);

  const characterSnippet = {
    name: AGENT_NAME,
    plugins: ["@1claw/plugin-elizaos"],
    settings: {
      secrets: {
        ONECLAW_AGENT_API_KEY: agentApiKey,
        ONECLAW_AGENT_ID: agentId,
        ONECLAW_VAULT_ID: vaultId,
        ONECLAW_BASE_URL: BASE_URL,
        ...(ENABLE_SHROUD ? { ONECLAW_USE_SHROUD: "true" } : {}),
      },
    },
  };

  info("--- Agent API key (save now — not retrievable later) ---");
  info(agentApiKey);
  info("\n--- elizaOS character snippet ---");
  console.log(JSON.stringify(characterSnippet, null, 2));

  info("\n--- Next steps ---");
  info(`1. Load env: export $(grep -v '^#' ${OUTPUT_FILE} | xargs)`);
  info("2. Store secrets in the vault via dashboard or PUT_SECRET");
  info("3. Add plugins: [\"@1claw/plugin-elizaos\"] to your character");
  info("4. Run: npm run validate (optional smoke test with ocv_ key)");
  info("\nBootstrap complete. Human key was not written to disk.");
}

main().catch((err) => {
  console.error(err instanceof Error ? err.message : err);
  process.exit(1);
});
